### ISSUE TITLE
Falsche Fehlermeldung in der Setzphase

### ISSUE THREAD

**Issue by GurkenKater** [lucaSchilling/OOThello#10]
In der Setzphase (Setze Randsteine) kommt beim Versuch auf ein Innenfeld zu setzen, die Fehlermeldung das es nicht erlaubt wäre auf ein Eckfeld zu setzen. Obwohl ich auf ein Innenfeld gesetzt habe.
---> Das eine Fehlermeldung kommt ist zwar richtig, aber es ist die falsche. 

LG

**Comment by lucaSchilling** [comment]
Sollte nun immer die Richtige Fehlermeldung ausgeben.
