### ISSUE TITLE
Eingabe "weiß" nicht erkannt/angenommen

### ISSUE THREAD

**Issue by GurkenKater** [lucaSchilling/OOThello#8]
Hi!
Im Menü bei der Abfrage der Farbe die man sein möchte wird "weiss" als Eingabe zwar erkannt, aber "weiß" mit "ß" nicht.
Bei "weiß" kommt die Exception: Ungültige Eingabe, sollte aber als weiß erkannt werden.

**Comment by lucaSchilling** [comment]
So is jetzt fixed, danke für die anmerkung
