### ISSUE TITLE
Ausgabe einer ominösen Matrix (DIE MATRIX? O.O)

### ISSUE THREAD

**Issue by GurkenKater** [lucaSchilling/OOThello#9]
Es taucht noch eine fragwürdige Matrix auf, wenn man durchs Menü navigiert.
Die taucht auf nach der Frage, welchen Schwierigkeitsgrad der Computer haben soll und schwer ausgewählt wird. Bei den anderen Schwierigkeitsgraden taucht das nicht auf.
Eingaben:
Name: asdfjöawlj
Farbe: schwarz
spielen
Gegen Computer: 1
Spielfeldgröße: 6
Schwierigkeitsgrad: schwer

**Comment by lucaSchilling** [comment]
Die Ausgabe war noch von meinen Tests drinne habe sie jetzt entfernt sollte jetzt passen
